package lojalucasberickw;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class uLoja extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(uLoja.class.getName());

    /**
     * Creates new form UlOJA
     */
    public uLoja() {
        initComponents();

        tf_IDProduto.setEditable(false);
        tf_IDProduto.setFocusable(false);

        tf_IDProduto.setForeground(java.awt.Color.GRAY);
        tf_NomeProduto.setForeground(java.awt.Color.GRAY);
        tf_MarcaProduto.setForeground(java.awt.Color.GRAY);
        tf_ValorProduto.setForeground(java.awt.Color.GRAY);
        tf_EstoqueProduto.setForeground(java.awt.Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInserir = new javax.swing.JButton();
        tf_IDProduto = new javax.swing.JTextField();
        tf_NomeProduto = new javax.swing.JTextField();
        tf_MarcaProduto = new javax.swing.JTextField();
        tf_ValorProduto = new javax.swing.JTextField();
        tf_EstoqueProduto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(this::btnInserirActionPerformed);

        tf_IDProduto.setEditable(false);
        tf_IDProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_IDProduto.setText("ID do Produto");
        tf_IDProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_IDProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_IDProdutoFocusLost(evt);
            }
        });

        tf_NomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_NomeProduto.setText("Nome do Produto");
        tf_NomeProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_NomeProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_NomeProdutoFocusLost(evt);
            }
        });

        tf_MarcaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_MarcaProduto.setText("Marca do Produto");
        tf_MarcaProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_MarcaProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_MarcaProdutoFocusLost(evt);
            }
        });

        tf_ValorProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_ValorProduto.setText("Valor do Produto (R$)");
        tf_ValorProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_ValorProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_ValorProdutoFocusLost(evt);
            }
        });

        tf_EstoqueProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_EstoqueProduto.setText("Quantidade em Estoque");
        tf_EstoqueProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_EstoqueProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_EstoqueProdutoFocusLost(evt);
            }
        });
        tf_EstoqueProduto.addActionListener(this::tf_EstoqueProdutoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_EstoqueProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_MarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_IDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tf_IDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_ValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_EstoqueProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        String sql = """
        INSERT INTO Produtos
        (nomeProduto, marcaProduto, valorProduto, qtdeEstoque)
        VALUES (?, ?, ?, ?)
        """;

        try (
                Connection con = DatabaseConnection.Connect(); PreparedStatement stmt = con.prepareStatement(
                sql,
                java.sql.Statement.RETURN_GENERATED_KEYS
        )) {

            stmt.setString(1, tf_NomeProduto.getText());
            stmt.setString(2, tf_MarcaProduto.getText());

            stmt.setBigDecimal(
                    3,
                    new java.math.BigDecimal(
                            tf_ValorProduto.getText().replace(",", ".")
                    )
            );

            stmt.setInt(
                    4,
                    Integer.parseInt(tf_EstoqueProduto.getText())
            );

            stmt.executeUpdate();

            ResultSet rs = stmt.getGeneratedKeys();

            if (rs.next()) {
                tf_IDProduto.setText(
                        String.valueOf(rs.getInt(1))
                );

                tf_IDProduto.setForeground(
                        javax.swing.UIManager.getColor("TextField.foreground")
                );
            }

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Produto cadastrado com sucesso!"
            );

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao cadastrar produto:\n" + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    // ================================= FOCUS GAINED ==================================== //
    private void tf_IDProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_IDProdutoFocusGained
        if (tf_IDProduto.getText().equals("ID do Produto")) {
            tf_IDProduto.setText("");
            tf_IDProduto.setForeground(
                    javax.swing.UIManager.getColor("TextField.foreground")
            );
        }
    }//GEN-LAST:event_tf_IDProdutoFocusGained

    private void tf_NomeProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_NomeProdutoFocusGained
        if (tf_NomeProduto.getText().equals("Nome do Produto")) {
            tf_NomeProduto.setText("");
            tf_NomeProduto.setForeground(
                    javax.swing.UIManager.getColor("TextField.foreground")
            );
        }
    }//GEN-LAST:event_tf_NomeProdutoFocusGained

    private void tf_MarcaProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_MarcaProdutoFocusGained
        if (tf_MarcaProduto.getText().equals("Marca do Produto")) {
            tf_MarcaProduto.setText("");
            tf_MarcaProduto.setForeground(
                    javax.swing.UIManager.getColor("TextField.foreground")
            );
        }
    }//GEN-LAST:event_tf_MarcaProdutoFocusGained

    private void tf_ValorProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_ValorProdutoFocusGained
        if (tf_ValorProduto.getText().equals("Valor do Produto (R$)")) {
            tf_ValorProduto.setText("");
            tf_ValorProduto.setForeground(
                    javax.swing.UIManager.getColor("TextField.foreground")
            );
        }
    }//GEN-LAST:event_tf_ValorProdutoFocusGained

    private void tf_EstoqueProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_EstoqueProdutoFocusGained
        if (tf_EstoqueProduto.getText().equals("Quantidade em Estoque")) {
            tf_EstoqueProduto.setText("");
            tf_EstoqueProduto.setForeground(
                    javax.swing.UIManager.getColor("TextField.foreground")
            );
        }
    }//GEN-LAST:event_tf_EstoqueProdutoFocusGained

    private void tf_EstoqueProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_EstoqueProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EstoqueProdutoActionPerformed

    // ================================= FOCUS LOST ================================== //
    private void tf_IDProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_IDProdutoFocusLost
        if (tf_IDProduto.getText().isBlank()) {
            tf_IDProduto.setText("ID do Produto");
            tf_IDProduto.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_tf_IDProdutoFocusLost

    private void tf_NomeProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_NomeProdutoFocusLost
        if (tf_NomeProduto.getText().isBlank()) {
            tf_NomeProduto.setText("Nome do Produto");
            tf_NomeProduto.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_tf_NomeProdutoFocusLost

    private void tf_MarcaProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_MarcaProdutoFocusLost
        if (tf_MarcaProduto.getText().isBlank()) {
            tf_MarcaProduto.setText("Marca do Produto");
            tf_MarcaProduto.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_tf_MarcaProdutoFocusLost

    private void tf_ValorProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_ValorProdutoFocusLost
        if (tf_ValorProduto.getText().isBlank()) {
            tf_ValorProduto.setText("Valor do Produto (R$)");
            tf_ValorProduto.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_tf_ValorProdutoFocusLost

    private void tf_EstoqueProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_EstoqueProdutoFocusLost
        if (tf_EstoqueProduto.getText().isBlank()) {
            tf_EstoqueProduto.setText("Quantidade em Estoque");
            tf_EstoqueProduto.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_tf_EstoqueProdutoFocusLost

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> new uLoja().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JTextField tf_EstoqueProduto;
    private javax.swing.JTextField tf_IDProduto;
    private javax.swing.JTextField tf_MarcaProduto;
    private javax.swing.JTextField tf_NomeProduto;
    private javax.swing.JTextField tf_ValorProduto;
    // End of variables declaration//GEN-END:variables
}
